version: '3.4'

services:
  gotodos:
    image: gotodos:0.0.1
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${PORT}:${PORT} 
    environment:
      - PORT=${PORT}
      - APP_ENV=${APP_ENV}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOSTV2}
    volumes:
      - ./logs:/logs 
      - ./uploads:/uploads
    links:
      - db
