version: '3.4'

services:
  redis:
      container_name: redis
      image: redis:6.2.6-alpine
      environment:
      - ALLOW_EMPTY_PASSWORD=yes
      ports:
      - 6379:6379
      volumes:
       - ./_data/redis:/data
       - ./config/redis_cfg/redis.conf:/redis.conf
      command: redis-server /redis.conf
  webapi:
    image: gotodos:0.0.1
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${PORT}:${PORT} 
    environment:
      - PORT=${PORT}
      - APP_ENV=${APP_ENV}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOSTV2}
      - REDIS_HOST=${DB_HOSTV2}
    volumes:
      - ./logs:/logs 
      - ./uploads:/uploads
