version: '3.4'

services:
  db:
      container_name: postgres
      image: postgres:14.1
      environment:
        POSTGRES_DB: todos
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: passw0rd
      restart: always
      ports:
        - 5432:5432
      volumes:
        - ./_data/pg_data:/var/lib/postgresql/data 
  redis:
      container_name: redis
      image: redis:6.2.6-alpine
      environment:
      - ALLOW_EMPTY_PASSWORD=yes
      ports:
      - 6379:6379
      volumes:
       - ./_data/redis:/data
       - ./config/redis_cfg/redis.conf:/redis.conf
      command: redis-server /redis.conf
  webapi:
    image: sing3demons/gotodos:0.0.9
    container_name: wabapi
    restart: always
    ports:
      - 8080:8080 
    environment:
      - PORT=${PORT}
      - APP_ENV=${APP_ENV}
      - REDIS_HOST=redis
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DSN=host=db user=postgres password=passw0rd dbname=todos port=5432  sslmode=disable TimeZone=Asia/Bangkok
    volumes:
      - ./uploads:/uploads
    depends_on:
        - db
        - redis
    links:
        - "db:db"
