version: '3.4'

services:
  gotodos:
    image: gotodos
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${PORT}:${PORT} 
    environment:
      - PORT=${PORT}
      - APP_ENV=${APP_ENV}
    volumes:
      - ./logs:/logs 
