apiVersion: v1
kind: PersistentVolume
metadata:
  name: gotodos-pv
  namespace: gotodos
spec:
  storageClassName: manual                    # Storage class. A PV Claim requesting the same storageClass can be bound to this volume.
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:                                   # hostPath PersistentVolume is used for development and testing. It uses a file/directory on the Node to emulate network-attached storage
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain       # Retain the PV even after PVC is deleted. 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gotodos-pvc
  namespace: gotodos
  labels:
    app: gotodos
spec:                                         # Access mode and resource limits
  storageClassName: manual                    # Request a certain storage class
  accessModes:
    - ReadWriteMany                           # ReadWriteMany means the volume can be mounted as read-write by many Nodes
  resources:
    requests:
      storage: 5Gi