apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotodos
  namespace: gotodos
spec:
  selector:
    matchLabels:
      app: gotodos
  template:
    metadata:
      labels:
        app: gotodos
    spec:
      containers:
        - name: gotodos
          image: sing3demons/gotodos:0.0.7
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - cat
                - /tmp/live
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 30
            failureThreshold: 5
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  key: REDIS
                  name: go-secret
              # value: redis-client
            - name: PORT
              value: "8080"
            - name: DSN
              valueFrom:
                secretKeyRef:
                  key: dsn
                  name: go-secret
            - name: APP_ENV
              value: production
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET_KEY
                  name: go-secret
          volumeMounts:
            - mountPath: /uploads
              name: go-todo
      volumes:
        - name: go-todo
          persistentVolumeClaim:
            claimName: gotodos-pvc
