version: '3.9'
services:
    db:
      container_name: postgres
      image: postgres:14.1
      environment:
        POSTGRES_DB: todos
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: passw0rd
      restart: always
      ports:
        - 5432:5432
      volumes:
        - ../_data/pg_data:/var/lib/postgresql/data 
    # redis:
    #   container_name: redis
    #   image: redis:6.2.6-alpine
    #   environment:
    #   - ALLOW_EMPTY_PASSWORD=yes
    #   ports:
    #   - 6379:6379
    #   volumes:
    #    - ../_data/redis:/data
    #    - ../config/redis_cfg/redis.conf:/redis.conf
    #   command: redis-server /redis.conf