@apiUrl=http://127.0.0.1:8080/api/v1
### Login 
POST {{apiUrl}}/auth/sign-in HTTP/1.1
Content-Type: application/json

{
    "email": "admin@dev.com",
    "password": "admin1234"
}

### Register 
POST {{apiUrl}}/auth/sign-up HTTP/1.1
Content-Type: application/json

{
    "email": "admin@dev.com",
    "password": "admin1234",
    "first_name": "admin",
    "last_name": "admin"
}


### User
GET {{apiUrl}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDY2MjQ5NzMsImlhdCI6MTY0NjUzODU3Mywic3ViIjoiMSJ9.r-tiDe-vs0iDFVYt5KrMt1KKyfKaNO8rRYUHYVu98yQ
